// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C case1 and case0 functions
#ifndef OMITCASE1
	/* BEGIN-AUTOGENERATED-C-CASE1-FUNCTION-DECLARATIONS */
	void CWE605_Multiple_Binds_Same_Port__basic_15_case1();

	void CWE605_Multiple_Binds_Same_Port__basic_08_case1();

	void CWE605_Multiple_Binds_Same_Port__basic_16_case1();

	void CWE605_Multiple_Binds_Same_Port__basic_11_case1();

	void CWE605_Multiple_Binds_Same_Port__basic_17_case1();

	void CWE605_Multiple_Binds_Same_Port__basic_01_case1();

	void CWE605_Multiple_Binds_Same_Port__basic_04_case1();

	void CWE605_Multiple_Binds_Same_Port__basic_13_case1();

	void CWE605_Multiple_Binds_Same_Port__basic_02_case1();

	void CWE605_Multiple_Binds_Same_Port__basic_05_case1();

	void CWE605_Multiple_Binds_Same_Port__basic_18_case1();

	void CWE605_Multiple_Binds_Same_Port__basic_06_case1();

	void CWE605_Multiple_Binds_Same_Port__basic_10_case1();

	void CWE605_Multiple_Binds_Same_Port__basic_14_case1();

	void CWE605_Multiple_Binds_Same_Port__basic_12_case1();

	void CWE605_Multiple_Binds_Same_Port__basic_03_case1();

	void CWE605_Multiple_Binds_Same_Port__basic_09_case1();

	void CWE605_Multiple_Binds_Same_Port__basic_07_case1();

	/* END-AUTOGENERATED-C-CASE1-FUNCTION-DECLARATIONS */
#endif // OMITCASE1


#ifndef OMITCASE0
	/* BEGIN-AUTOGENERATED-C-CASE0-FUNCTION-DECLARATIONS */
	void CWE605_Multiple_Binds_Same_Port__basic_15_case0();

	void CWE605_Multiple_Binds_Same_Port__basic_08_case0();

	void CWE605_Multiple_Binds_Same_Port__basic_16_case0();

	void CWE605_Multiple_Binds_Same_Port__basic_11_case0();

	void CWE605_Multiple_Binds_Same_Port__basic_17_case0();

	void CWE605_Multiple_Binds_Same_Port__basic_01_case0();

	void CWE605_Multiple_Binds_Same_Port__basic_04_case0();

	void CWE605_Multiple_Binds_Same_Port__basic_13_case0();

	void CWE605_Multiple_Binds_Same_Port__basic_02_case0();

	void CWE605_Multiple_Binds_Same_Port__basic_05_case0();

	void CWE605_Multiple_Binds_Same_Port__basic_18_case0();

	void CWE605_Multiple_Binds_Same_Port__basic_06_case0();

	void CWE605_Multiple_Binds_Same_Port__basic_10_case0();

	void CWE605_Multiple_Binds_Same_Port__basic_14_case0();

	void CWE605_Multiple_Binds_Same_Port__basic_12_case0();

	void CWE605_Multiple_Binds_Same_Port__basic_03_case0();

	void CWE605_Multiple_Binds_Same_Port__basic_09_case0();

	void CWE605_Multiple_Binds_Same_Port__basic_07_case0();

	/* END-AUTOGENERATED-C-CASE0-FUNCTION-DECLARATIONS */
#endif // OMITCASE0

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and case1 and case0 functions

#ifndef OMITCASE1
	/* BEGIN-AUTOGENERATED-CPP-CASE1-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-CASE1-FUNCTION-DECLARATIONS */
#endif // OMITCASE1


#ifndef OMITCASE0
	/* BEGIN-AUTOGENERATED-CPP-CASE0-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-CASE0-FUNCTION-DECLARATIONS */
#endif // OMITCASE0


#endif // __cplusplus


#endif //  _TESTCASES_H
