// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C case1 and case0 functions
#ifndef OMITCASE1
	/* BEGIN-AUTOGENERATED-C-CASE1-FUNCTION-DECLARATIONS */
	void CWE665_Improper_Initialization__char_cat_17_case1();

	void CWE665_Improper_Initialization__char_cat_13_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_22_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_51_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_11_case1();

	void CWE665_Improper_Initialization__char_cat_42_case1();

	void CWE665_Improper_Initialization__char_ncat_14_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_03_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_34_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_12_case1();

	void CWE665_Improper_Initialization__char_cat_21_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_41_case1();

	void CWE665_Improper_Initialization__char_ncat_63_case1();

	void CWE665_Improper_Initialization__char_ncat_54_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_14_case1();

	void CWE665_Improper_Initialization__char_ncat_03_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_61_case1();

	void CWE665_Improper_Initialization__char_cat_63_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_03_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_01_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_61_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_68_case1();

	void CWE665_Improper_Initialization__char_cat_18_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_16_case1();

	void CWE665_Improper_Initialization__char_cat_02_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_52_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_10_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_54_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_53_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_04_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_14_case1();

	void CWE665_Improper_Initialization__char_ncat_31_case1();

	void CWE665_Improper_Initialization__char_cat_51_case1();

	void CWE665_Improper_Initialization__char_ncat_05_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_65_case1();

	void CWE665_Improper_Initialization__char_ncat_61_case1();

	void CWE665_Improper_Initialization__char_cat_52_case1();

	void CWE665_Improper_Initialization__char_cat_08_case1();

	void CWE665_Improper_Initialization__char_cat_32_case1();

	void CWE665_Improper_Initialization__char_cat_67_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_44_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_10_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_65_case1();

	void CWE665_Improper_Initialization__char_cat_11_case1();

	void CWE665_Improper_Initialization__char_cat_09_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_21_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_41_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_21_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_52_case1();

	void CWE665_Improper_Initialization__char_cat_66_case1();

	void CWE665_Improper_Initialization__char_cat_44_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_31_case1();

	void CWE665_Improper_Initialization__char_ncat_12_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_08_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_06_case1();

	void CWE665_Improper_Initialization__char_ncat_06_case1();

	void CWE665_Improper_Initialization__char_ncat_45_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_07_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_18_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_08_case1();

	void CWE665_Improper_Initialization__char_ncat_04_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_68_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_64_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_15_case1();

	void CWE665_Improper_Initialization__char_ncat_09_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_07_case1();

	void CWE665_Improper_Initialization__char_ncat_16_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_32_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_31_case1();

	void CWE665_Improper_Initialization__char_cat_16_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_17_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_09_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_64_case1();

	void CWE665_Improper_Initialization__char_ncat_21_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_67_case1();

	void CWE665_Improper_Initialization__char_cat_01_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_02_case1();

	void CWE665_Improper_Initialization__char_cat_14_case1();

	void CWE665_Improper_Initialization__char_cat_05_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_06_case1();

	void CWE665_Improper_Initialization__char_ncat_44_case1();

	void CWE665_Improper_Initialization__char_ncat_42_case1();

	void CWE665_Improper_Initialization__char_cat_22_case1();

	void CWE665_Improper_Initialization__char_ncat_02_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_02_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_11_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_54_case1();

	void CWE665_Improper_Initialization__char_ncat_08_case1();

	void CWE665_Improper_Initialization__char_cat_34_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_13_case1();

	void CWE665_Improper_Initialization__char_ncat_32_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_17_case1();

	void CWE665_Improper_Initialization__char_cat_64_case1();

	void CWE665_Improper_Initialization__char_cat_12_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_45_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_09_case1();

	void CWE665_Improper_Initialization__char_cat_07_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_01_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_63_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_67_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_51_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_66_case1();

	void CWE665_Improper_Initialization__char_ncat_07_case1();

	void CWE665_Improper_Initialization__char_cat_41_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_05_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_66_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_12_case1();

	void CWE665_Improper_Initialization__char_cat_68_case1();

	void CWE665_Improper_Initialization__char_ncat_22_case1();

	void CWE665_Improper_Initialization__char_ncat_53_case1();

	void CWE665_Improper_Initialization__char_cat_10_case1();

	void CWE665_Improper_Initialization__char_ncat_51_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_45_case1();

	void CWE665_Improper_Initialization__char_cat_45_case1();

	void CWE665_Improper_Initialization__char_ncat_41_case1();

	void CWE665_Improper_Initialization__char_ncat_34_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_05_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_04_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_42_case1();

	void CWE665_Improper_Initialization__char_ncat_18_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_44_case1();

	void CWE665_Improper_Initialization__char_ncat_52_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_22_case1();

	void CWE665_Improper_Initialization__char_ncat_15_case1();

	void CWE665_Improper_Initialization__char_ncat_65_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_13_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_34_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_32_case1();

	void CWE665_Improper_Initialization__char_ncat_11_case1();

	void CWE665_Improper_Initialization__char_ncat_10_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_16_case1();

	void CWE665_Improper_Initialization__char_cat_54_case1();

	void CWE665_Improper_Initialization__char_ncat_13_case1();

	void CWE665_Improper_Initialization__char_ncat_64_case1();

	void CWE665_Improper_Initialization__char_cat_31_case1();

	void CWE665_Improper_Initialization__char_cat_04_case1();

	void CWE665_Improper_Initialization__char_cat_03_case1();

	void CWE665_Improper_Initialization__char_ncat_68_case1();

	void CWE665_Improper_Initialization__char_ncat_17_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_53_case1();

	void CWE665_Improper_Initialization__wchar_t_ncat_15_case1();

	void CWE665_Improper_Initialization__char_cat_61_case1();

	void CWE665_Improper_Initialization__char_cat_65_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_63_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_18_case1();

	void CWE665_Improper_Initialization__char_cat_53_case1();

	void CWE665_Improper_Initialization__char_ncat_67_case1();

	void CWE665_Improper_Initialization__char_ncat_66_case1();

	void CWE665_Improper_Initialization__wchar_t_cat_42_case1();

	void CWE665_Improper_Initialization__char_cat_15_case1();

	void CWE665_Improper_Initialization__char_cat_06_case1();

	void CWE665_Improper_Initialization__char_ncat_01_case1();

	/* END-AUTOGENERATED-C-CASE1-FUNCTION-DECLARATIONS */
#endif // OMITCASE1


#ifndef OMITCASE0
	/* BEGIN-AUTOGENERATED-C-CASE0-FUNCTION-DECLARATIONS */
	void CWE665_Improper_Initialization__char_cat_17_case0();

	void CWE665_Improper_Initialization__char_cat_13_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_22_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_51_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_11_case0();

	void CWE665_Improper_Initialization__char_cat_42_case0();

	void CWE665_Improper_Initialization__char_ncat_14_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_03_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_34_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_12_case0();

	void CWE665_Improper_Initialization__char_cat_21_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_41_case0();

	void CWE665_Improper_Initialization__char_ncat_63_case0();

	void CWE665_Improper_Initialization__char_ncat_54_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_14_case0();

	void CWE665_Improper_Initialization__char_ncat_03_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_61_case0();

	void CWE665_Improper_Initialization__char_cat_63_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_03_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_01_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_61_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_68_case0();

	void CWE665_Improper_Initialization__char_cat_18_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_16_case0();

	void CWE665_Improper_Initialization__char_cat_02_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_52_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_10_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_54_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_53_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_04_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_14_case0();

	void CWE665_Improper_Initialization__char_ncat_31_case0();

	void CWE665_Improper_Initialization__char_cat_51_case0();

	void CWE665_Improper_Initialization__char_ncat_05_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_65_case0();

	void CWE665_Improper_Initialization__char_ncat_61_case0();

	void CWE665_Improper_Initialization__char_cat_52_case0();

	void CWE665_Improper_Initialization__char_cat_08_case0();

	void CWE665_Improper_Initialization__char_cat_32_case0();

	void CWE665_Improper_Initialization__char_cat_67_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_44_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_10_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_65_case0();

	void CWE665_Improper_Initialization__char_cat_11_case0();

	void CWE665_Improper_Initialization__char_cat_09_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_21_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_41_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_21_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_52_case0();

	void CWE665_Improper_Initialization__char_cat_66_case0();

	void CWE665_Improper_Initialization__char_cat_44_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_31_case0();

	void CWE665_Improper_Initialization__char_ncat_12_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_08_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_06_case0();

	void CWE665_Improper_Initialization__char_ncat_06_case0();

	void CWE665_Improper_Initialization__char_ncat_45_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_07_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_18_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_08_case0();

	void CWE665_Improper_Initialization__char_ncat_04_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_68_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_64_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_15_case0();

	void CWE665_Improper_Initialization__char_ncat_09_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_07_case0();

	void CWE665_Improper_Initialization__char_ncat_16_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_32_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_31_case0();

	void CWE665_Improper_Initialization__char_cat_16_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_17_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_09_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_64_case0();

	void CWE665_Improper_Initialization__char_ncat_21_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_67_case0();

	void CWE665_Improper_Initialization__char_cat_01_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_02_case0();

	void CWE665_Improper_Initialization__char_cat_14_case0();

	void CWE665_Improper_Initialization__char_cat_05_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_06_case0();

	void CWE665_Improper_Initialization__char_ncat_44_case0();

	void CWE665_Improper_Initialization__char_ncat_42_case0();

	void CWE665_Improper_Initialization__char_cat_22_case0();

	void CWE665_Improper_Initialization__char_ncat_02_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_02_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_11_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_54_case0();

	void CWE665_Improper_Initialization__char_ncat_08_case0();

	void CWE665_Improper_Initialization__char_cat_34_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_13_case0();

	void CWE665_Improper_Initialization__char_ncat_32_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_17_case0();

	void CWE665_Improper_Initialization__char_cat_64_case0();

	void CWE665_Improper_Initialization__char_cat_12_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_45_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_09_case0();

	void CWE665_Improper_Initialization__char_cat_07_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_01_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_63_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_67_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_51_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_66_case0();

	void CWE665_Improper_Initialization__char_ncat_07_case0();

	void CWE665_Improper_Initialization__char_cat_41_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_05_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_66_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_12_case0();

	void CWE665_Improper_Initialization__char_cat_68_case0();

	void CWE665_Improper_Initialization__char_ncat_22_case0();

	void CWE665_Improper_Initialization__char_ncat_53_case0();

	void CWE665_Improper_Initialization__char_cat_10_case0();

	void CWE665_Improper_Initialization__char_ncat_51_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_45_case0();

	void CWE665_Improper_Initialization__char_cat_45_case0();

	void CWE665_Improper_Initialization__char_ncat_41_case0();

	void CWE665_Improper_Initialization__char_ncat_34_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_05_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_04_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_42_case0();

	void CWE665_Improper_Initialization__char_ncat_18_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_44_case0();

	void CWE665_Improper_Initialization__char_ncat_52_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_22_case0();

	void CWE665_Improper_Initialization__char_ncat_15_case0();

	void CWE665_Improper_Initialization__char_ncat_65_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_13_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_34_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_32_case0();

	void CWE665_Improper_Initialization__char_ncat_11_case0();

	void CWE665_Improper_Initialization__char_ncat_10_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_16_case0();

	void CWE665_Improper_Initialization__char_cat_54_case0();

	void CWE665_Improper_Initialization__char_ncat_13_case0();

	void CWE665_Improper_Initialization__char_ncat_64_case0();

	void CWE665_Improper_Initialization__char_cat_31_case0();

	void CWE665_Improper_Initialization__char_cat_04_case0();

	void CWE665_Improper_Initialization__char_cat_03_case0();

	void CWE665_Improper_Initialization__char_ncat_68_case0();

	void CWE665_Improper_Initialization__char_ncat_17_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_53_case0();

	void CWE665_Improper_Initialization__wchar_t_ncat_15_case0();

	void CWE665_Improper_Initialization__char_cat_61_case0();

	void CWE665_Improper_Initialization__char_cat_65_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_63_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_18_case0();

	void CWE665_Improper_Initialization__char_cat_53_case0();

	void CWE665_Improper_Initialization__char_ncat_67_case0();

	void CWE665_Improper_Initialization__char_ncat_66_case0();

	void CWE665_Improper_Initialization__wchar_t_cat_42_case0();

	void CWE665_Improper_Initialization__char_cat_15_case0();

	void CWE665_Improper_Initialization__char_cat_06_case0();

	void CWE665_Improper_Initialization__char_ncat_01_case0();

	/* END-AUTOGENERATED-C-CASE0-FUNCTION-DECLARATIONS */
#endif // OMITCASE0

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and case1 and case0 functions

#ifndef OMITCASE1
	/* BEGIN-AUTOGENERATED-CPP-CASE1-FUNCTION-DECLARATIONS */
	namespace CWE665_Improper_Initialization__wchar_t_cat_43 { void case1();}

	namespace CWE665_Improper_Initialization__char_ncat_62 { void case1();}

	namespace CWE665_Improper_Initialization__char_ncat_83 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_33 { void case1();}

	namespace CWE665_Improper_Initialization__char_cat_73 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_72 { void case1();}

	namespace CWE665_Improper_Initialization__char_cat_83 { void case1();}

	namespace CWE665_Improper_Initialization__char_ncat_33 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_81 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_84 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_84 { void case1();}

	namespace CWE665_Improper_Initialization__char_ncat_74 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_73 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_84 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_43 { void case1();}

	namespace CWE665_Improper_Initialization__char_cat_84 { void case1();}

	namespace CWE665_Improper_Initialization__char_cat_83 { void case1();}

	namespace CWE665_Improper_Initialization__char_ncat_84 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_73 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_62 { void case1();}

	namespace CWE665_Improper_Initialization__char_ncat_81 { void case1();}

	namespace CWE665_Improper_Initialization__char_cat_82 { void case1();}

	namespace CWE665_Improper_Initialization__char_ncat_43 { void case1();}

	namespace CWE665_Improper_Initialization__char_cat_72 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_84 { void case1();}

	namespace CWE665_Improper_Initialization__char_cat_43 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_83 { void case1();}

	namespace CWE665_Improper_Initialization__char_ncat_72 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_83 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_74 { void case1();}

	namespace CWE665_Improper_Initialization__char_cat_81 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_83 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_74 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_62 { void case1();}

	namespace CWE665_Improper_Initialization__char_cat_84 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_83 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_81 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_82 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_33 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_72 { void case1();}

	namespace CWE665_Improper_Initialization__char_cat_62 { void case1();}

	namespace CWE665_Improper_Initialization__char_cat_33 { void case1();}

	namespace CWE665_Improper_Initialization__char_ncat_82 { void case1();}

	namespace CWE665_Improper_Initialization__char_ncat_84 { void case1();}

	namespace CWE665_Improper_Initialization__char_cat_74 { void case1();}

	namespace CWE665_Improper_Initialization__char_ncat_83 { void case1();}

	namespace CWE665_Improper_Initialization__char_ncat_73 { void case1();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_82 { void case1();}

	namespace CWE665_Improper_Initialization__class_01 { void case1();}

	/* END-AUTOGENERATED-CPP-CASE1-FUNCTION-DECLARATIONS */
#endif // OMITCASE1


#ifndef OMITCASE0
	/* BEGIN-AUTOGENERATED-CPP-CASE0-FUNCTION-DECLARATIONS */
	namespace CWE665_Improper_Initialization__wchar_t_cat_43 { void case0();}

	namespace CWE665_Improper_Initialization__char_ncat_62 { void case0();}

	namespace CWE665_Improper_Initialization__char_ncat_83 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_33 { void case0();}

	namespace CWE665_Improper_Initialization__char_cat_73 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_72 { void case0();}

	namespace CWE665_Improper_Initialization__char_cat_83 { void case0();}

	namespace CWE665_Improper_Initialization__char_ncat_33 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_81 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_84 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_84 { void case0();}

	namespace CWE665_Improper_Initialization__char_ncat_74 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_73 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_84 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_43 { void case0();}

	namespace CWE665_Improper_Initialization__char_cat_84 { void case0();}

	namespace CWE665_Improper_Initialization__char_cat_83 { void case0();}

	namespace CWE665_Improper_Initialization__char_ncat_84 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_73 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_62 { void case0();}

	namespace CWE665_Improper_Initialization__char_ncat_81 { void case0();}

	namespace CWE665_Improper_Initialization__char_cat_82 { void case0();}

	namespace CWE665_Improper_Initialization__char_ncat_43 { void case0();}

	namespace CWE665_Improper_Initialization__char_cat_72 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_84 { void case0();}

	namespace CWE665_Improper_Initialization__char_cat_43 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_83 { void case0();}

	namespace CWE665_Improper_Initialization__char_ncat_72 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_83 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_74 { void case0();}

	namespace CWE665_Improper_Initialization__char_cat_81 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_83 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_74 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_62 { void case0();}

	namespace CWE665_Improper_Initialization__char_cat_84 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_83 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_81 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_82 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_33 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_ncat_72 { void case0();}

	namespace CWE665_Improper_Initialization__char_cat_62 { void case0();}

	namespace CWE665_Improper_Initialization__char_cat_33 { void case0();}

	namespace CWE665_Improper_Initialization__char_ncat_82 { void case0();}

	namespace CWE665_Improper_Initialization__char_ncat_84 { void case0();}

	namespace CWE665_Improper_Initialization__char_cat_74 { void case0();}

	namespace CWE665_Improper_Initialization__char_ncat_83 { void case0();}

	namespace CWE665_Improper_Initialization__char_ncat_73 { void case0();}

	namespace CWE665_Improper_Initialization__wchar_t_cat_82 { void case0();}

	namespace CWE665_Improper_Initialization__class_01 { void case0();}

	/* END-AUTOGENERATED-CPP-CASE0-FUNCTION-DECLARATIONS */
#endif // OMITCASE0


#endif // __cplusplus


#endif //  _TESTCASES_H
