#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Align Stage A samples back to SecVulEval targets")
    parser.add_argument(
        "--targets",
        default="out/secvuleval/targets.jsonl",
        help="targets file generated by secvuleval_prepare.py",
    )
    parser.add_argument(
        "--samples",
        required=True,
        help="Stage A raw sample output (samples.raw.jsonl or equivalent)",
    )
    parser.add_argument(
        "--output",
        default="out/secvuleval/targets.aligned.jsonl",
        help="aligned output path",
    )
    return parser.parse_args()


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            records.append(json.loads(line))
    return records


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2)
        handle.write("\n")


def write_jsonl(path: Path, records: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for record in records:
            handle.write(json.dumps(record, ensure_ascii=False))
            handle.write("\n")


def sample_key(sample: dict[str, Any]) -> tuple[str, str, str]:
    entrypoint = sample.get("entrypoint") or {}
    return (
        str(sample.get("project_id", "")).strip(),
        str(entrypoint.get("file", "")).strip(),
        str(entrypoint.get("function", "")).strip(),
    )


def main() -> None:
    args = parse_args()
    targets_path = Path(args.targets).resolve()
    samples_path = Path(args.samples).resolve()
    output_path = Path(args.output).resolve()

    if not targets_path.exists():
        print(f"targets file not found: {targets_path}", file=sys.stderr)
        raise SystemExit(1)
    if not samples_path.exists():
        print(f"samples file not found: {samples_path}", file=sys.stderr)
        raise SystemExit(1)

    targets = read_jsonl(targets_path)
    samples = read_jsonl(samples_path)

    samples_by_key: dict[tuple[str, str, str], list[dict[str, Any]]] = defaultdict(list)
    for sample in samples:
        key = sample_key(sample)
        if all(key):
            samples_by_key[key].append(sample)

    aligned_records: list[dict[str, Any]] = []
    matched_target_count = 0
    total_attached_samples = 0
    vulnerable_matched_count = 0
    non_vulnerable_matched_count = 0

    for target in targets:
        key = (
            str(target.get("project_id", "")).strip(),
            str(target.get("filepath", "")).strip(),
            str(target.get("func_name", "")).strip(),
        )
        matched_samples = samples_by_key.get(key, [])
        sample_refs = []
        for sample in matched_samples:
            sample_refs.append(
                {
                    "sample_id": str(sample.get("sample_id", "")).strip(),
                    "entrypoint": sample.get("entrypoint", {}),
                    "focus": sample.get("focus", {}),
                    "graph_stats": sample.get("graph_stats", {}),
                    "analysis_warnings": sample.get("analysis_warnings", []),
                    "seed": {
                        "id": str(sample.get("seed", {}).get("id", "")).strip(),
                        "api": str(sample.get("seed", {}).get("api", "")).strip(),
                        "token": str(sample.get("seed", {}).get("token", "")).strip(),
                        "line": int(sample.get("seed", {}).get("line", 0) or 0),
                    },
                    "sink_locs": sample.get("sink_locs", []),
                    "sink_candidates": sample.get("sink_candidates", []),
                    "source_candidates": sample.get("source_candidates", []),
                    "source_sink_flows": sample.get("source_sink_flows", []),
                    "stats_record_path": samples_path.with_name(samples_path.name.replace(".raw.", ".stats.")).name,
                    "llm_record_path": samples_path.with_name(samples_path.name.replace(".raw.", ".llm.")).name,
                }
            )

        aligned = dict(target)
        aligned["sample_match_count"] = len(sample_refs)
        aligned["matched"] = bool(sample_refs)
        aligned["sample_refs"] = sample_refs
        aligned_records.append(aligned)

        if sample_refs:
            matched_target_count += 1
            total_attached_samples += len(sample_refs)
            if bool(target.get("is_vulnerable")):
                vulnerable_matched_count += 1
            else:
                non_vulnerable_matched_count += 1

    write_jsonl(output_path, aligned_records)
    write_json(
        output_path.with_suffix(".summary.json"),
        {
            "generated_at": utc_now(),
            "targets": str(targets_path),
            "samples": str(samples_path),
            "output": str(output_path),
            "target_count": len(targets),
            "sample_count": len(samples),
            "matched_target_count": matched_target_count,
            "unmatched_target_count": len(targets) - matched_target_count,
            "vulnerable_target_count": sum(1 for target in targets if bool(target.get("is_vulnerable"))),
            "non_vulnerable_target_count": sum(1 for target in targets if not bool(target.get("is_vulnerable"))),
            "vulnerable_matched_count": vulnerable_matched_count,
            "non_vulnerable_matched_count": non_vulnerable_matched_count,
            "total_attached_samples": total_attached_samples,
        },
    )

    print(
        f"aligned {matched_target_count}/{len(targets)} targets to Stage A samples "
        f"using project_id + filepath + func_name",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
