// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C case1 and case0 functions
#ifndef OMITCASE1
	/* BEGIN-AUTOGENERATED-C-CASE1-FUNCTION-DECLARATIONS */
	void CWE401_Memory_Leak__wchar_t_malloc_51_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_61_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_32_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_64_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_32_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_17_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_65_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_31_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_68_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_15_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_52_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_15_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_42_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_42_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_16_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_05_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_63_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_02_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_45_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_45_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_22_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_03_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_07_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_07_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_41_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_65_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_12_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_45_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_65_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_18_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_12_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_02_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_04_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_44_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_68_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_03_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_13_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_08_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_14_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_32_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_54_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_17_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_34_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_09_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_61_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_14_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_15_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_52_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_01_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_03_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_65_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_61_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_03_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_11_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_54_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_52_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_64_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_61_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_11_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_06_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_54_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_05_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_22_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_06_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_01_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_08_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_22_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_05_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_04_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_03_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_10_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_65_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_61_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_34_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_67_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_09_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_02_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_02_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_68_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_05_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_64_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_51_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_18_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_42_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_21_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_03_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_67_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_51_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_14_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_22_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_44_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_06_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_68_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_44_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_67_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_32_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_53_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_12_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_32_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_52_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_45_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_65_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_18_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_52_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_45_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_13_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_66_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_53_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_01_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_65_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_07_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_41_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_10_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_44_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_13_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_42_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_11_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_05_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_04_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_45_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_14_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_13_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_34_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_12_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_05_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_01_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_22_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_08_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_08_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_08_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_06_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_31_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_10_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_68_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_14_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_22_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_10_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_16_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_42_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_11_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_05_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_17_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_03_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_61_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_64_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_13_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_10_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_32_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_03_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_18_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_41_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_42_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_44_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_44_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_66_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_31_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_16_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_65_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_41_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_61_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_63_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_54_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_66_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_15_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_41_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_31_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_63_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_32_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_41_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_11_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_31_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_16_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_14_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_66_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_07_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_22_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_04_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_66_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_15_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_66_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_53_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_07_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_34_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_65_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_34_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_61_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_16_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_68_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_17_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_66_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_63_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_12_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_09_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_67_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_01_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_42_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_17_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_53_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_16_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_06_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_07_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_18_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_63_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_02_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_18_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_42_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_42_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_02_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_17_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_15_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_16_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_45_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_04_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_64_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_16_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_67_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_12_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_06_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_61_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_16_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_68_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_04_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_67_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_21_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_05_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_11_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_64_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_34_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_63_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_51_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_21_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_64_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_15_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_53_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_04_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_61_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_07_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_64_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_01_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_66_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_21_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_09_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_54_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_15_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_02_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_32_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_67_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_54_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_08_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_09_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_08_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_13_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_52_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_54_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_67_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_63_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_34_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_06_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_42_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_68_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_03_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_04_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_32_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_13_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_31_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_22_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_10_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_34_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_13_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_67_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_63_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_67_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_53_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_21_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_01_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_66_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_07_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_45_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_10_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_52_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_65_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_41_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_44_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_05_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_18_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_52_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_06_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_41_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_11_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_09_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_10_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_08_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_16_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_34_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_09_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_34_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_15_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_02_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_52_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_41_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_68_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_09_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_15_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_07_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_12_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_12_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_66_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_17_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_63_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_07_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_31_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_51_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_21_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_05_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_21_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_13_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_01_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_51_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_44_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_03_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_11_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_18_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_09_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_12_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_51_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_12_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_08_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_53_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_01_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_22_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_13_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_51_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_54_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_51_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_45_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_17_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_17_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_11_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_14_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_53_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_52_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_04_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_10_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_10_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_09_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_51_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_63_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_54_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_31_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_44_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_06_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_53_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_21_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_64_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_02_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_32_case1();

	void CWE401_Memory_Leak__strdup_wchar_t_21_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_53_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_64_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_22_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_06_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_18_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_17_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_31_case1();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_14_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_11_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_54_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_21_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_18_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_45_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_14_case1();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_31_case1();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_14_case1();

	void CWE401_Memory_Leak__wchar_t_malloc_08_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_04_case1();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_68_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_01_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_41_case1();

	void CWE401_Memory_Leak__wchar_t_realloc_44_case1();

	void CWE401_Memory_Leak__wchar_t_calloc_02_case1();

	/* END-AUTOGENERATED-C-CASE1-FUNCTION-DECLARATIONS */
#endif // OMITCASE1


#ifndef OMITCASE0
	/* BEGIN-AUTOGENERATED-C-CASE0-FUNCTION-DECLARATIONS */
	void CWE401_Memory_Leak__wchar_t_malloc_51_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_61_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_32_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_64_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_32_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_17_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_65_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_31_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_68_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_15_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_52_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_15_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_42_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_42_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_16_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_05_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_63_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_02_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_45_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_45_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_22_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_03_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_07_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_07_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_41_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_65_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_12_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_45_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_65_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_18_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_12_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_02_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_04_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_44_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_68_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_03_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_13_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_08_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_14_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_32_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_54_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_17_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_34_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_09_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_61_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_14_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_15_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_52_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_01_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_03_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_65_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_61_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_03_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_11_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_54_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_52_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_64_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_61_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_11_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_06_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_54_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_05_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_22_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_06_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_01_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_08_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_22_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_05_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_04_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_03_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_10_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_65_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_61_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_34_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_67_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_09_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_02_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_02_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_68_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_05_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_64_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_51_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_18_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_42_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_21_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_03_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_67_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_51_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_14_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_22_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_44_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_06_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_68_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_44_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_67_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_32_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_53_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_12_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_32_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_52_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_45_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_65_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_18_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_52_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_45_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_13_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_66_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_53_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_01_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_65_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_07_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_41_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_10_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_44_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_13_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_42_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_11_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_05_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_04_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_45_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_14_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_13_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_34_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_12_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_05_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_01_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_22_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_08_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_08_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_08_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_06_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_31_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_10_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_68_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_14_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_22_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_10_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_16_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_42_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_11_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_05_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_17_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_03_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_61_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_64_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_13_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_10_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_32_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_03_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_18_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_41_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_42_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_44_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_44_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_66_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_31_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_16_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_65_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_41_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_61_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_63_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_54_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_66_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_15_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_41_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_31_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_63_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_32_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_41_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_11_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_31_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_16_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_14_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_66_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_07_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_22_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_04_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_66_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_15_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_66_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_53_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_07_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_34_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_65_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_34_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_61_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_16_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_68_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_17_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_66_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_63_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_12_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_09_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_67_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_01_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_42_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_17_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_53_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_16_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_06_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_07_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_18_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_63_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_02_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_18_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_42_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_42_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_02_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_17_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_15_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_16_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_45_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_04_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_64_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_16_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_67_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_12_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_06_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_61_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_16_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_68_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_04_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_67_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_21_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_05_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_11_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_64_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_34_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_63_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_51_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_21_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_64_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_15_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_53_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_04_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_61_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_07_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_64_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_01_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_66_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_21_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_09_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_54_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_15_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_02_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_32_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_67_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_54_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_08_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_09_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_08_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_13_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_52_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_54_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_67_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_63_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_34_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_06_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_42_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_68_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_03_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_04_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_32_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_13_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_31_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_22_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_10_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_34_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_13_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_67_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_63_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_67_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_53_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_21_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_01_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_66_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_07_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_45_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_10_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_52_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_65_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_41_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_44_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_05_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_18_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_52_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_06_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_41_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_11_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_09_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_10_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_08_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_16_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_34_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_09_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_34_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_15_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_02_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_52_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_41_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_68_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_09_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_15_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_07_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_12_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_12_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_66_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_17_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_63_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_07_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_31_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_51_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_21_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_05_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_21_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_13_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_01_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_51_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_44_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_03_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_11_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_18_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_09_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_12_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_51_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_12_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_08_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_53_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_01_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_22_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_13_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_51_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_54_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_51_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_45_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_17_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_17_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_11_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_14_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_53_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_52_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_04_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_10_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_10_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_09_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_51_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_63_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_54_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_31_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_44_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_06_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_53_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_21_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_64_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_02_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_32_case0();

	void CWE401_Memory_Leak__strdup_wchar_t_21_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_53_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_64_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_22_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_06_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_18_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_17_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_31_case0();

	void CWE401_Memory_Leak__twoIntsStruct_malloc_14_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_11_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_realloc_54_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_21_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_18_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_45_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_malloc_14_case0();

	void CWE401_Memory_Leak__struct_twoIntsStruct_calloc_31_case0();

	void CWE401_Memory_Leak__twoIntsStruct_realloc_14_case0();

	void CWE401_Memory_Leak__wchar_t_malloc_08_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_04_case0();

	void CWE401_Memory_Leak__twoIntsStruct_calloc_68_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_01_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_41_case0();

	void CWE401_Memory_Leak__wchar_t_realloc_44_case0();

	void CWE401_Memory_Leak__wchar_t_calloc_02_case0();

	/* END-AUTOGENERATED-C-CASE0-FUNCTION-DECLARATIONS */
#endif // OMITCASE0

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and case1 and case0 functions

#ifndef OMITCASE1
	/* BEGIN-AUTOGENERATED-CPP-CASE1-FUNCTION-DECLARATIONS */
	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_83 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_83 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_73 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_62 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_73 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_33 { void case1();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_81 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_73 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_84 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_62 { void case1();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_83 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_62 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_33 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_73 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_73 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_81 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_83 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_84 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_74 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_84 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_82 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_43 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_84 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_72 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_83 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_72 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_72 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_62 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_83 { void case1();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_72 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_43 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_72 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_84 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_83 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_62 { void case1();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_74 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_72 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_82 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_83 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_43 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_81 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_81 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_82 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_43 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_83 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_84 { void case1();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_82 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_33 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_83 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_73 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_62 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_84 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_83 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_74 { void case1();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_83 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_84 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_82 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_83 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_84 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_33 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_82 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_73 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_84 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_84 { void case1();}

	namespace CWE401_Memory_Leak__virtual_destructor_01 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_83 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_82 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_43 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_72 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_81 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_84 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_72 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_84 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_82 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_82 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_72 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_74 { void case1();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_84 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_33 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_43 { void case1();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_62 { void case1();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_73 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_62 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_74 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_43 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_74 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_81 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_74 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_33 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_33 { void case1();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_84 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_74 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_82 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_72 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_62 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_81 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_73 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_43 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_73 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_43 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_83 { void case1();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_43 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_84 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_81 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_83 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_33 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_74 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_84 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_83 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_84 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_84 { void case1();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_33 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_33 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_83 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_62 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_74 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_81 { void case1();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_81 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_83 { void case1();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_83 { void case1();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_84 { void case1();}

	/* END-AUTOGENERATED-CPP-CASE1-FUNCTION-DECLARATIONS */
#endif // OMITCASE1


#ifndef OMITCASE0
	/* BEGIN-AUTOGENERATED-CPP-CASE0-FUNCTION-DECLARATIONS */
	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_83 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_83 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_73 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_62 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_73 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_33 { void case0();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_81 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_73 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_84 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_62 { void case0();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_83 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_62 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_33 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_73 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_73 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_81 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_83 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_84 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_74 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_84 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_82 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_43 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_84 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_72 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_83 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_72 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_72 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_62 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_83 { void case0();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_72 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_43 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_72 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_84 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_83 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_62 { void case0();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_74 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_72 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_82 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_83 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_43 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_81 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_81 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_82 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_43 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_83 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_84 { void case0();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_82 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_33 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_83 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_73 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_62 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_84 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_83 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_74 { void case0();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_83 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_84 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_82 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_83 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_84 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_33 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_82 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_73 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_84 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_84 { void case0();}

	namespace CWE401_Memory_Leak__virtual_destructor_01 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_83 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_82 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_43 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_72 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_81 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_84 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_72 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_84 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_82 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_82 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_72 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_74 { void case0();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_84 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_33 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_43 { void case0();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_62 { void case0();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_73 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_62 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_74 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_43 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_74 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_81 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_74 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_33 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_33 { void case0();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_84 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_74 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_82 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_72 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_62 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_81 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_realloc_73 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_43 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_73 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_malloc_43 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_calloc_83 { void case0();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_43 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_84 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_81 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_83 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_33 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_74 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_84 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_83 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_84 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_84 { void case0();}

	namespace CWE401_Memory_Leak__strdup_wchar_t_33 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_realloc_33 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_malloc_83 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_62 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_74 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_calloc_81 { void case0();}

	namespace CWE401_Memory_Leak__struct_twoIntsStruct_malloc_81 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_83 { void case0();}

	namespace CWE401_Memory_Leak__twoIntsStruct_calloc_83 { void case0();}

	namespace CWE401_Memory_Leak__wchar_t_realloc_84 { void case0();}

	/* END-AUTOGENERATED-CPP-CASE0-FUNCTION-DECLARATIONS */
#endif // OMITCASE0


#endif // __cplusplus


#endif //  _TESTCASES_H
