// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C case1 and case0 functions
#ifndef OMITCASE1
	/* BEGIN-AUTOGENERATED-C-CASE1-FUNCTION-DECLARATIONS */
	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_13_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_67_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_01_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_53_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_02_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_02_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_18_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_11_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_32_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_31_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_32_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_51_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_44_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_11_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_06_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_16_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_64_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_21_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_45_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_68_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_13_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_02_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_22_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_09_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_64_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_41_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_51_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_04_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_21_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_09_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_45_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_15_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_03_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_22_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_10_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_01_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_34_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_45_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_15_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_18_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_66_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_51_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_04_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_32_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_14_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_01_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_65_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_41_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_09_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_54_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_61_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_67_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_05_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_51_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_13_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_03_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_02_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_11_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_08_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_67_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_04_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_08_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_16_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_34_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_21_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_07_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_12_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_07_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_04_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_42_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_16_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_63_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_52_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_65_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_44_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_34_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_61_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_65_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_03_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_12_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_10_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_16_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_52_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_11_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_63_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_64_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_65_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_66_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_66_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_42_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_07_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_17_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_13_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_31_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_67_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_22_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_45_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_06_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_54_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_07_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_15_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_42_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_06_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_09_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_12_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_17_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_68_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_34_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_31_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_44_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_21_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_61_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_54_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_05_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_68_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_12_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_14_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_10_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_18_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_08_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_44_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_41_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_17_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_17_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_14_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_41_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_63_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_10_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_31_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_03_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_05_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_52_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_08_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_52_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_32_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_53_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_66_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_01_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_06_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_68_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_22_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_53_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_53_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_18_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_54_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_64_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_61_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_14_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_05_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_42_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_15_case1();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_63_case1();

	/* END-AUTOGENERATED-C-CASE1-FUNCTION-DECLARATIONS */
#endif // OMITCASE1


#ifndef OMITCASE0
	/* BEGIN-AUTOGENERATED-C-CASE0-FUNCTION-DECLARATIONS */
	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_13_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_67_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_01_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_53_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_02_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_02_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_18_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_11_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_32_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_31_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_32_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_51_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_44_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_11_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_06_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_16_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_64_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_21_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_45_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_68_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_13_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_02_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_22_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_09_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_64_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_41_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_51_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_04_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_21_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_09_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_45_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_15_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_03_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_22_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_10_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_01_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_34_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_45_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_15_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_18_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_66_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_51_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_04_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_32_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_14_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_01_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_65_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_41_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_09_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_54_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_61_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_67_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_05_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_51_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_13_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_03_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_02_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_11_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_08_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_67_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_04_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_08_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_16_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_34_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_21_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_07_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_12_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_07_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_04_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_42_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_16_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_63_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_52_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_65_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_44_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_34_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_61_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_65_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_03_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_12_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_10_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_16_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_52_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_11_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_63_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_64_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_65_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_66_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_66_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_42_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_07_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_17_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_13_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_31_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_67_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_22_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_45_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_06_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_54_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_07_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_15_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_42_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_06_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_09_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_12_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_17_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_68_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_34_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_31_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_44_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_21_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_61_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_54_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_05_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_68_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_12_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_14_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_10_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_18_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_08_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_44_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_41_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_17_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_17_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_14_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_41_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_63_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_10_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_31_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_03_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_05_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_52_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_08_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_52_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_32_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_53_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_66_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_01_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_06_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_68_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_22_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_53_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_53_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_18_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_54_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_64_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_61_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_14_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_05_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_42_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_15_case0();

	void CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_63_case0();

	/* END-AUTOGENERATED-C-CASE0-FUNCTION-DECLARATIONS */
#endif // OMITCASE0

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and case1 and case0 functions

#ifndef OMITCASE1
	/* BEGIN-AUTOGENERATED-CPP-CASE1-FUNCTION-DECLARATIONS */
	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_84 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_74 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_33 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_74 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_73 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_33 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_33 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_72 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_83 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_72 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_62 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_43 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_73 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_84 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_73 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_82 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_82 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_43 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_82 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_83 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_84 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_62 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_84 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_43 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_84 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_84 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_81 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_83 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_81 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_84 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_83 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_83 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_81 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_83 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_73 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_33 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_62 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_83 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_72 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_81 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_82 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_62 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_74 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_83 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_43 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_74 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_84 { void case1();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_72 { void case1();}

	/* END-AUTOGENERATED-CPP-CASE1-FUNCTION-DECLARATIONS */
#endif // OMITCASE1


#ifndef OMITCASE0
	/* BEGIN-AUTOGENERATED-CPP-CASE0-FUNCTION-DECLARATIONS */
	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_84 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_74 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_33 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_74 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_73 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_33 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_33 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_72 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_83 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_72 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_62 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_43 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_73 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_84 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_73 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_82 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_82 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_43 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_82 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_83 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_84 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_62 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_84 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_43 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_84 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_84 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_81 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_83 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_81 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_84 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_83 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_83 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_81 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_83 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_73 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_33 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_62 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_83 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnvp_72 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_81 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnv_82 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_62 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_74 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_83 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_43 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_spawnlp_74 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_84 { void case0();}

	namespace CWE78_OS_Command_Injection__wchar_t_listen_socket_w32_execv_72 { void case0();}

	/* END-AUTOGENERATED-CPP-CASE0-FUNCTION-DECLARATIONS */
#endif // OMITCASE0


#endif // __cplusplus


#endif //  _TESTCASES_H
