// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C case1 and case0 functions
#ifndef OMITCASE1
	/* BEGIN-AUTOGENERATED-C-CASE1-FUNCTION-DECLARATIONS */
	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_08_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_54_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_45_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_67_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_12_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_02_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_18_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_16_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_10_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_01_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_44_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_12_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_54_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_41_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_04_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_66_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_16_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_04_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_14_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_13_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_66_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_51_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_45_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_08_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_03_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_09_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_12_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_41_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_52_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_04_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_32_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_02_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_13_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_09_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_32_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_67_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_44_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_03_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_04_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_63_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_54_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_08_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_17_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_07_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_15_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_13_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_44_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_31_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_13_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_14_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_06_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_07_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_66_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_31_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_17_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_10_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_01_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_31_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_18_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_64_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_11_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_41_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_03_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_11_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_31_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_52_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_01_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_10_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_14_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_67_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_14_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_64_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_05_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_18_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_44_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_12_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_07_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_68_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_11_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_45_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_08_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_02_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_68_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_63_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_32_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_11_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_44_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_14_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_05_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_53_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_53_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_13_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_32_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_66_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_10_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_09_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_06_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_12_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_01_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_63_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_51_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_11_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_04_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_45_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_14_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_44_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_05_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_54_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_07_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_15_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_68_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_31_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_02_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_18_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_34_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_32_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_12_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_52_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_45_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_17_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_15_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_34_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_17_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_05_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_09_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_02_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_01_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_16_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_12_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_34_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_14_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_63_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_07_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_03_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_10_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_53_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_51_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_17_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_05_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_52_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_08_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_52_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_41_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_67_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_53_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_65_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_68_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_67_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_66_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_65_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_44_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_16_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_64_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_67_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_15_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_13_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_68_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_08_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_45_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_66_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_68_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_53_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_34_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_51_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_18_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_52_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_52_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_64_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_53_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_04_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_34_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_53_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_41_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_45_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_06_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_09_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_67_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_18_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_65_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_32_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_18_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_04_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_16_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_03_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_05_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_54_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_31_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_64_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_31_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_06_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_63_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_10_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_64_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_10_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_07_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_08_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_51_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_11_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_03_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_66_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_03_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_41_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_63_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_15_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_65_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_09_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_65_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_54_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_15_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_54_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_02_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_02_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_06_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_01_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_01_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_05_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_13_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_32_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_17_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_41_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_51_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_34_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_09_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_64_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_51_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_16_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_34_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_11_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_06_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_16_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_68_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_07_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_65_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_63_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_17_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_65_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_06_case1();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_15_case1();

	/* END-AUTOGENERATED-C-CASE1-FUNCTION-DECLARATIONS */
#endif // OMITCASE1


#ifndef OMITCASE0
	/* BEGIN-AUTOGENERATED-C-CASE0-FUNCTION-DECLARATIONS */
	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_08_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_54_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_45_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_67_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_12_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_02_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_18_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_16_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_10_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_01_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_44_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_12_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_54_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_41_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_04_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_66_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_16_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_04_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_14_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_13_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_66_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_51_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_45_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_08_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_03_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_09_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_12_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_41_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_52_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_04_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_32_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_02_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_13_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_09_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_32_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_67_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_44_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_03_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_04_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_63_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_54_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_08_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_17_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_07_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_15_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_13_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_44_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_31_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_13_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_14_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_06_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_07_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_66_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_31_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_17_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_10_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_01_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_31_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_18_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_64_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_11_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_41_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_03_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_11_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_31_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_52_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_01_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_10_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_14_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_67_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_14_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_64_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_05_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_18_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_44_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_12_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_07_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_68_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_11_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_45_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_08_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_02_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_68_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_63_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_32_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_11_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_44_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_14_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_05_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_53_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_53_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_13_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_32_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_66_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_10_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_09_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_06_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_12_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_01_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_63_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_51_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_11_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_04_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_45_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_14_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_44_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_05_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_54_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_07_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_15_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_68_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_31_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_02_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_18_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_34_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_32_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_12_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_52_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_45_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_17_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_15_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_34_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_17_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_05_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_09_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_02_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_01_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_16_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_12_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_34_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_14_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_63_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_07_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_03_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_10_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_53_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_51_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_17_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_05_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_52_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_08_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_52_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_41_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_67_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_53_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_65_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_68_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_67_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_66_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_65_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_44_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_16_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_64_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_67_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_15_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_13_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_68_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_08_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_45_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_66_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_68_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_53_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_34_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_51_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_18_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_52_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_52_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_64_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_53_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_04_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_34_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_53_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_41_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_45_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_06_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_09_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_67_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_18_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_65_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_32_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_18_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_04_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_16_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_03_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_05_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_54_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_31_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_64_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_31_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_06_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_63_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_10_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_64_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_10_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_07_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_08_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_51_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_11_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_03_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_66_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_03_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_41_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_63_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_15_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_65_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_09_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_65_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_54_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_15_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_54_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_02_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_02_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_06_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_01_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_01_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_05_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_13_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_32_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_17_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_41_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_51_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_34_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_09_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_64_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_51_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_16_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_34_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_11_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_06_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_16_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_68_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_07_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_declare_65_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_static_63_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_17_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_65_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_long_static_06_case0();

	void CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_15_case0();

	/* END-AUTOGENERATED-C-CASE0-FUNCTION-DECLARATIONS */
#endif // OMITCASE0

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and case1 and case0 functions

#ifndef OMITCASE1
	/* BEGIN-AUTOGENERATED-CPP-CASE1-FUNCTION-DECLARATIONS */
	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_static_74 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_declare_74 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_declare_33 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_declare_81 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_long_static_73 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_long_static_74 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_82 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_long_static_82 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_static_82 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_static_73 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_33 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_33 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_81 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_73 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_static_72 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_declare_73 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_72 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_74 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_static_81 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_73 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_72 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_74 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_long_static_33 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_long_static_72 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_81 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_81 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_declare_72 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_declare_82 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_81 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_72 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_72 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_82 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_74 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_73 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_82 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_82 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_33 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_73 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_33 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_74 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_long_static_81 { void case1();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_static_33 { void case1();}

	/* END-AUTOGENERATED-CPP-CASE1-FUNCTION-DECLARATIONS */
#endif // OMITCASE1


#ifndef OMITCASE0
	/* BEGIN-AUTOGENERATED-CPP-CASE0-FUNCTION-DECLARATIONS */
	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_static_74 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_declare_74 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_declare_33 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_declare_81 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_long_static_73 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_long_static_74 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_82 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_long_static_82 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_static_82 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_static_73 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_33 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_33 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_81 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_73 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_static_72 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_declare_73 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_72 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_74 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_static_81 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_73 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_72 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_74 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_long_static_33 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_long_static_72 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_81 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_81 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_declare_72 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_declare_82 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_81 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_72 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_72 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_82 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_74 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_73 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_82 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_82 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_33 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_73 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_33 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_74 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_long_static_81 { void case0();}

	namespace CWE590_Free_Memory_Not_on_Heap__free_struct_static_33 { void case0();}

	/* END-AUTOGENERATED-CPP-CASE0-FUNCTION-DECLARATIONS */
#endif // OMITCASE0


#endif // __cplusplus


#endif //  _TESTCASES_H
