/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITCASE1

	/* Calling C case1 functions */
	/* BEGIN-AUTOGENERATED-C-CASE1-FUNCTION-CALLS */
	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_05_case1();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_05_case1();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_09_case1();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_09_case1();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_14_case1();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_14_case1();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_07_case1();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_07_case1();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_17_case1();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_17_case1();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_15_case1();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_15_case1();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_06_case1();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_06_case1();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_02_case1();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_02_case1();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_10_case1();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_10_case1();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_08_case1();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_08_case1();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_03_case1();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_03_case1();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_04_case1();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_04_case1();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_12_case1();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_12_case1();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_13_case1();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_13_case1();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_01_case1();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_01_case1();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_16_case1();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_16_case1();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_18_case1();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_18_case1();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_11_case1();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_11_case1();

	/* END-AUTOGENERATED-C-CASE1-FUNCTION-CALLS */





#ifdef __cplusplus
	/* Calling C++ case1 functions */
	/* BEGIN-AUTOGENERATED-CPP-CASE1-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-CASE1-FUNCTION-CALLS */

#endif /* __cplusplus */

#endif /* OMITCASE1 */

#ifndef OMITCASE0

	/* Calling C case0 functions */
	/* BEGIN-AUTOGENERATED-C-CASE0-FUNCTION-CALLS */
	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_05_case0();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_05_case0();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_09_case0();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_09_case0();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_14_case0();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_14_case0();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_07_case0();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_07_case0();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_17_case0();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_17_case0();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_15_case0();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_15_case0();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_06_case0();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_06_case0();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_02_case0();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_02_case0();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_10_case0();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_10_case0();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_08_case0();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_08_case0();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_03_case0();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_03_case0();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_04_case0();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_04_case0();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_12_case0();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_12_case0();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_13_case0();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_13_case0();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_01_case0();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_01_case0();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_16_case0();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_16_case0();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_18_case0();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_18_case0();

	printLine("Calling CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_11_case0();");
	CWE832_Unlock_of_Resource_That_is_Not_Locked__basic_11_case0();

	/* END-AUTOGENERATED-C-CASE0-FUNCTION-CALLS */




	
#ifdef __cplusplus
	/* Calling C++ case0 functions */
	/* BEGIN-AUTOGENERATED-CPP-CASE0-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-CASE0-FUNCTION-CALLS */
	
#endif /* __cplusplus */

#endif /* OMITCASE0 */

	return 0;

} 
