// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C case1 and case0 functions
#ifndef OMITCASE1
	/* BEGIN-AUTOGENERATED-C-CASE1-FUNCTION-DECLARATIONS */
	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_05_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_66_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_13_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_21_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_44_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_51_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_14_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_17_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_04_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_10_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_17_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_64_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_16_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_64_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_11_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_34_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_18_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_02_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_13_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_12_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_53_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_44_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_65_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_21_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_31_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_04_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_68_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_22_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_12_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_03_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_54_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_31_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_45_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_45_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_14_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_63_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_53_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_15_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_18_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_22_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_05_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_65_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_18_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_14_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_61_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_22_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_17_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_44_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_32_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_10_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_52_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_63_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_32_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_41_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_54_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_21_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_08_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_05_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_41_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_03_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_53_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_05_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_02_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_04_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_04_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_42_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_09_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_64_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_11_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_12_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_53_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_01_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_10_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_54_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_09_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_17_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_63_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_21_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_09_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_61_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_66_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_07_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_41_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_11_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_42_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_34_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_61_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_16_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_34_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_67_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_41_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_15_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_68_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_02_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_06_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_67_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_32_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_54_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_06_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_67_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_03_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_61_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_42_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_13_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_13_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_65_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_16_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_01_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_01_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_34_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_65_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_11_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_52_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_51_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_16_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_08_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_66_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_08_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_22_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_12_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_44_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_52_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_31_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_14_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_07_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_64_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_06_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_63_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_45_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_32_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_06_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_07_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_52_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_67_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_07_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_45_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_03_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_02_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_09_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_66_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_10_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_08_case1();

	void CWE675_Duplicate_Operations_on_Resource__fopen_42_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_68_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_68_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_31_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_01_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_18_case1();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_15_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_15_case1();

	void CWE675_Duplicate_Operations_on_Resource__open_51_case1();

	void CWE675_Duplicate_Operations_on_Resource__freopen_51_case1();

	/* END-AUTOGENERATED-C-CASE1-FUNCTION-DECLARATIONS */
#endif // OMITCASE1


#ifndef OMITCASE0
	/* BEGIN-AUTOGENERATED-C-CASE0-FUNCTION-DECLARATIONS */
	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_05_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_66_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_13_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_21_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_44_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_51_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_14_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_17_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_04_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_10_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_17_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_64_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_16_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_64_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_11_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_34_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_18_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_02_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_13_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_12_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_53_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_44_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_65_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_21_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_31_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_04_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_68_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_22_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_12_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_03_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_54_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_31_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_45_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_45_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_14_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_63_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_53_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_15_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_18_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_22_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_05_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_65_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_18_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_14_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_61_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_22_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_17_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_44_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_32_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_10_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_52_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_63_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_32_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_41_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_54_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_21_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_08_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_05_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_41_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_03_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_53_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_05_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_02_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_04_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_04_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_42_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_09_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_64_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_11_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_12_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_53_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_01_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_10_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_54_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_09_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_17_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_63_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_21_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_09_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_61_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_66_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_07_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_41_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_11_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_42_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_34_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_61_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_16_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_34_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_67_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_41_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_15_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_68_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_02_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_06_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_67_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_32_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_54_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_06_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_67_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_03_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_61_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_42_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_13_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_13_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_65_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_16_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_01_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_01_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_34_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_65_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_11_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_52_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_51_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_16_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_08_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_66_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_08_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_22_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_12_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_44_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_52_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_31_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_14_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_07_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_64_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_06_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_63_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_45_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_32_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_06_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_07_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_52_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_67_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_07_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_45_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_03_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_02_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_09_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_66_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_10_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_08_case0();

	void CWE675_Duplicate_Operations_on_Resource__fopen_42_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_68_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_68_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_31_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_01_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_18_case0();

	void CWE675_Duplicate_Operations_on_Resource__w32CreateFile_15_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_15_case0();

	void CWE675_Duplicate_Operations_on_Resource__open_51_case0();

	void CWE675_Duplicate_Operations_on_Resource__freopen_51_case0();

	/* END-AUTOGENERATED-C-CASE0-FUNCTION-DECLARATIONS */
#endif // OMITCASE0

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and case1 and case0 functions

#ifndef OMITCASE1
	/* BEGIN-AUTOGENERATED-CPP-CASE1-FUNCTION-DECLARATIONS */
	namespace CWE675_Duplicate_Operations_on_Resource__open_74 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_84 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_62 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_73 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_62 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_73 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_74 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_83 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_84 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_82 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_83 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_73 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_33 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_43 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_74 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_81 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_83 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_84 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_74 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_84 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_72 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_62 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_72 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_84 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_33 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_81 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_43 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_81 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_84 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_62 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_84 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_83 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_83 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_33 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_33 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_82 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_82 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_81 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_43 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_83 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_72 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_82 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_43 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_73 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_83 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_84 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_72 { void case1();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_83 { void case1();}

	/* END-AUTOGENERATED-CPP-CASE1-FUNCTION-DECLARATIONS */
#endif // OMITCASE1


#ifndef OMITCASE0
	/* BEGIN-AUTOGENERATED-CPP-CASE0-FUNCTION-DECLARATIONS */
	namespace CWE675_Duplicate_Operations_on_Resource__open_74 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_84 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_62 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_73 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_62 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_73 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_74 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_83 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_84 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_82 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_83 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_73 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_33 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_43 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_74 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_81 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_83 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_84 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_74 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_84 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_72 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_62 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_72 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_84 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_33 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_81 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_43 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_81 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_84 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_62 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_84 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_83 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__open_83 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_33 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_33 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_82 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_82 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_81 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_43 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_83 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_72 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_82 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_43 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_73 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__fopen_83 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__w32CreateFile_84 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_72 { void case0();}

	namespace CWE675_Duplicate_Operations_on_Resource__freopen_83 { void case0();}

	/* END-AUTOGENERATED-CPP-CASE0-FUNCTION-DECLARATIONS */
#endif // OMITCASE0


#endif // __cplusplus


#endif //  _TESTCASES_H
