// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C case1 and case0 functions
#ifndef OMITCASE1
	/* BEGIN-AUTOGENERATED-C-CASE1-FUNCTION-DECLARATIONS */
	void CWE124_Buffer_Underwrite__CWE839_negative_44_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_15_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_07_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_21_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_34_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_15_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_03_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_44_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_11_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_45_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_34_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_52_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_52_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_10_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_52_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_08_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_09_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_45_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_04_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_15_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_17_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_15_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_42_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_22_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_21_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_05_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_03_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_07_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_02_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_16_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_11_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_18_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_09_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_12_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_67_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_09_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_52_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_44_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_01_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_02_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_66_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_41_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_42_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_17_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_66_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_06_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_14_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_64_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_31_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_45_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_17_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_54_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_10_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_63_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_07_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_05_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_07_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_32_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_51_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_12_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_68_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_65_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_53_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_31_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_13_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_68_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_32_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_51_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_54_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_41_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_12_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_64_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_54_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_02_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_51_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_12_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_01_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_14_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_12_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_07_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_02_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_11_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_14_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_13_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_13_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_03_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_68_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_51_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_03_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_16_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_17_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_45_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_31_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_09_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_51_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_10_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_05_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_09_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_02_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_09_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_42_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_64_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_18_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_52_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_06_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_41_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_41_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_32_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_02_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_68_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_32_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_32_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_34_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_32_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_64_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_06_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_08_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_11_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_01_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_42_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_66_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_03_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_66_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_12_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_13_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_14_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_02_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_15_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_64_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_14_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_34_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_21_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_61_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_65_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_34_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_45_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_45_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_44_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_04_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_42_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_53_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_09_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_14_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_42_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_08_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_07_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_52_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_66_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_02_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_16_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_31_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_06_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_65_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_31_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_68_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_01_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_05_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_31_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_63_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_51_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_22_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_12_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_08_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_18_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_64_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_05_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_63_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_52_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_18_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_12_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_53_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_22_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_04_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_45_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_53_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_65_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_66_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_34_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_44_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_45_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_22_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_15_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_08_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_63_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_34_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_66_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_51_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_64_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_18_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_64_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_61_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_03_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_10_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_22_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_66_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_61_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_12_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_63_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_17_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_09_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_04_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_05_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_67_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_64_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_45_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_07_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_14_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_52_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_63_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_44_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_54_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_61_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_05_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_14_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_13_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_16_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_11_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_31_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_11_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_18_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_21_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_16_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_61_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_12_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_32_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_31_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_18_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_08_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_42_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_18_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_32_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_14_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_61_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_09_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_08_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_12_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_65_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_04_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_66_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_53_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_68_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_10_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_07_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_14_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_21_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_07_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_34_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_06_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_52_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_06_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_08_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_61_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_11_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_67_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_21_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_21_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_08_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_44_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_15_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_45_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_03_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_41_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_63_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_45_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_31_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_01_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_61_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_06_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_41_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_17_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_05_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_16_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_67_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_51_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_31_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_42_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_17_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_67_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_45_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_67_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_54_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_10_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_67_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_41_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_17_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_68_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_04_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_52_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_05_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_18_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_67_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_44_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_22_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_22_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_41_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_53_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_34_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_06_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_31_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_16_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_51_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_22_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_07_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_15_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_21_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_06_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_63_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_67_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_53_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_01_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_65_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_54_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_17_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_09_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_09_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_44_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_53_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_05_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_32_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_54_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_42_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_10_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_04_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_68_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_06_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_51_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_02_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_03_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_41_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_01_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_22_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_17_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_09_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_16_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_02_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_52_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_64_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_54_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_12_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_66_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_10_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_18_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_61_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_22_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_10_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_42_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_04_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_34_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_04_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_67_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_10_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_11_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_03_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_67_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_02_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_54_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_16_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_13_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_31_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_53_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_13_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_53_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_68_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_32_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_64_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_63_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_01_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_21_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_04_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_61_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_11_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_01_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_66_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_68_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_18_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_65_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_44_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_17_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_65_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_04_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_51_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_42_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_13_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_65_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_54_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_68_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_63_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_10_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_04_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_15_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_06_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_61_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_32_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_11_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_01_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_65_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_03_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_16_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_63_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_01_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_41_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_17_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_21_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_53_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_54_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_14_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_13_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_51_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_03_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_22_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_15_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_14_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_15_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_16_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_13_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_07_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_42_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_41_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_34_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_13_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_13_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_34_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_18_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_03_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_63_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_22_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_67_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_65_case1();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_08_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_52_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_66_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_01_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_08_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_11_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_15_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_32_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_05_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_16_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_44_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_68_case1();

	void CWE124_Buffer_Underwrite__CWE839_rand_05_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_54_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_02_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_21_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_21_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_65_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_53_case1();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_64_case1();

	void CWE124_Buffer_Underwrite__CWE839_negative_10_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_11_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_44_case1();

	void CWE124_Buffer_Underwrite__malloc_char_loop_08_case1();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_61_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_07_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_41_case1();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_06_case1();

	/* END-AUTOGENERATED-C-CASE1-FUNCTION-DECLARATIONS */
#endif // OMITCASE1


#ifndef OMITCASE0
	/* BEGIN-AUTOGENERATED-C-CASE0-FUNCTION-DECLARATIONS */
	void CWE124_Buffer_Underwrite__CWE839_negative_44_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_15_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_07_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_21_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_34_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_15_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_03_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_44_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_11_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_45_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_34_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_52_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_52_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_10_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_52_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_08_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_09_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_45_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_04_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_15_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_17_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_15_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_42_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_22_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_21_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_05_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_03_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_07_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_02_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_16_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_11_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_18_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_09_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_12_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_67_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_09_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_52_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_44_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_01_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_02_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_66_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_41_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_42_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_17_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_66_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_06_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_14_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_64_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_31_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_45_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_17_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_54_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_10_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_63_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_07_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_05_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_07_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_32_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_51_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_12_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_68_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_65_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_53_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_31_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_13_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_68_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_32_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_51_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_54_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_41_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_12_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_64_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_54_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_02_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_51_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_12_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_01_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_14_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_12_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_07_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_02_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_11_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_14_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_13_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_13_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_03_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_68_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_51_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_03_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_16_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_17_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_45_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_31_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_09_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_51_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_10_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_05_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_09_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_02_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_09_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_42_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_64_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_18_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_52_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_06_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_41_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_41_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_32_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_02_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_68_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_32_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_32_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_34_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_32_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_64_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_06_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_08_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_11_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_01_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_42_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_66_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_03_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_66_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_12_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_13_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_14_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_02_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_15_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_64_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_14_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_34_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_21_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_61_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_65_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_34_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_45_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_45_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_44_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_04_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_42_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_53_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_09_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_14_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_42_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_08_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_07_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_52_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_66_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_02_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_16_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_31_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_06_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_65_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_31_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_68_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_01_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_05_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_31_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_63_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_51_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_22_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_12_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_08_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_18_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_64_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_05_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_63_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_52_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_18_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_12_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_53_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_22_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_04_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_45_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_53_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_65_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_66_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_34_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_44_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_45_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_22_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_15_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_08_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_63_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_34_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_66_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_51_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_64_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_18_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_64_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_61_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_03_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_10_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_22_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_66_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_61_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_12_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_63_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_17_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_09_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_04_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_05_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_67_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_64_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_45_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_07_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_14_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_52_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_63_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_44_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_54_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_61_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_05_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_14_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_13_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_16_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_11_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_31_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_11_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_18_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_21_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_16_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_61_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_12_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_32_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_31_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_18_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_08_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_42_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_18_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_32_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_14_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_61_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_09_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_08_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_12_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_65_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_04_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_66_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_53_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_68_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_10_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_07_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_14_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_21_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_07_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_34_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_06_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_52_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_06_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_08_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_61_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_11_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_67_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_21_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_21_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_08_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_44_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_15_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_45_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_03_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_41_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_63_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_45_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_31_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_01_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_61_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_06_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_41_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_17_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_05_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_16_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_67_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_51_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_31_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_42_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_17_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_67_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_45_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_67_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_54_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_10_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_67_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_41_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_17_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_68_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_04_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_52_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_05_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_18_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_67_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_44_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_22_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_22_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_41_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_53_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_34_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_06_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_31_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_16_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_51_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_22_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_07_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_15_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_21_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_06_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_63_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_67_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_53_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_01_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_65_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_54_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_17_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_09_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_09_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_44_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_53_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_05_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_32_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_54_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_42_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_10_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_04_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_68_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_06_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_51_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_02_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_03_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_41_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_01_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_22_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_17_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_09_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_16_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_02_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_52_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_64_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_54_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_12_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_66_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_10_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_18_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_61_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_22_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_10_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_42_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_04_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_34_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_04_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_67_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_10_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_11_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_03_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_67_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_02_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_54_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_16_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_13_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_31_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_53_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_13_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_53_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_68_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_32_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_64_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_63_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_01_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_21_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_04_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_61_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_11_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_01_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_66_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_68_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_18_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_65_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_44_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_17_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_65_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_04_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_51_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_42_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_13_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_65_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_54_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_68_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_63_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_10_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_04_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_15_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_06_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_61_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_32_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_11_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_01_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_65_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_03_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_16_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_63_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_01_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_41_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_17_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_21_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_53_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_54_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_14_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_13_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_51_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_03_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_22_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_15_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_14_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_15_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_16_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_13_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_07_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_42_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_41_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_34_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_13_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_13_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_34_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_18_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_03_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_63_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_22_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_67_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_65_case0();

	void CWE124_Buffer_Underwrite__malloc_char_cpy_08_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_52_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_66_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_01_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_08_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_11_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_15_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_32_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_05_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_16_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_44_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_68_case0();

	void CWE124_Buffer_Underwrite__CWE839_rand_05_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_54_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_02_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_21_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memmove_21_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_65_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_loop_53_case0();

	void CWE124_Buffer_Underwrite__malloc_char_ncpy_64_case0();

	void CWE124_Buffer_Underwrite__CWE839_negative_10_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_11_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_44_case0();

	void CWE124_Buffer_Underwrite__malloc_char_loop_08_case0();

	void CWE124_Buffer_Underwrite__malloc_char_memcpy_61_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_07_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_41_case0();

	void CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_06_case0();

	/* END-AUTOGENERATED-C-CASE0-FUNCTION-DECLARATIONS */
#endif // OMITCASE0

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and case1 and case0 functions

#ifndef OMITCASE1
	/* BEGIN-AUTOGENERATED-CPP-CASE1-FUNCTION-DECLARATIONS */
	namespace CWE124_Buffer_Underwrite__malloc_char_loop_81 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_43 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_81 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_72 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_33 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_62 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_82 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_74 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_82 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_74 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_81 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_72 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_81 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_81 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_73 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_74 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_73 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_81 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_43 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_43 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_43 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_62 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_72 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_33 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_72 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_62 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_82 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_74 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_81 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_43 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_33 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_33 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_81 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_74 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_81 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_81 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_74 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_62 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_74 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_82 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_72 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_74 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_43 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_72 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_74 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_73 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_73 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_62 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_74 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_62 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_33 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_62 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_62 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_73 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_62 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_74 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_43 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_43 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_43 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_43 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_82 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_72 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_81 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_73 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_82 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_82 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_33 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_72 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_43 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_82 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_62 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_33 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_82 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_73 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_73 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_72 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_73 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_33 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_33 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_73 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_84 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_82 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_33 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_62 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_72 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_74 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_82 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_81 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_62 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_33 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_73 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_82 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_33 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_83 { void case1();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_73 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_72 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_72 { void case1();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_43 { void case1();}

	/* END-AUTOGENERATED-CPP-CASE1-FUNCTION-DECLARATIONS */
#endif // OMITCASE1


#ifndef OMITCASE0
	/* BEGIN-AUTOGENERATED-CPP-CASE0-FUNCTION-DECLARATIONS */
	namespace CWE124_Buffer_Underwrite__malloc_char_loop_81 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_43 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_81 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_72 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_33 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_62 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_82 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_74 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_82 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_74 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_81 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_72 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_81 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_81 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_73 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_74 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_73 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_81 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_43 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_43 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_43 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_62 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_72 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_33 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_72 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_62 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_82 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_74 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_81 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_43 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_33 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_33 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_81 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_74 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_81 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_81 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_74 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_62 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_74 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_82 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_72 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_74 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_43 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_72 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_74 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_73 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_73 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_62 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_74 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_62 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_33 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_62 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_62 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_73 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_62 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_74 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_43 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_43 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_43 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_43 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_82 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_72 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_81 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memmove_73 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_82 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_82 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_33 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_72 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_43 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_82 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_62 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_ncpy_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_33 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_82 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_73 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_73 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_72 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_cpy_73 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_33 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_33 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memcpy_73 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_84 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_rand_82 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_33 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_62 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_72 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_74 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_82 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_81 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_62 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_33 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_ncpy_73 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_cpy_82 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_33 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_loop_83 { void case0();}

	namespace CWE124_Buffer_Underwrite__CWE839_negative_73 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_memcpy_72 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_wchar_t_memmove_72 { void case0();}

	namespace CWE124_Buffer_Underwrite__malloc_char_loop_43 { void case0();}

	/* END-AUTOGENERATED-CPP-CASE0-FUNCTION-DECLARATIONS */
#endif // OMITCASE0


#endif // __cplusplus


#endif //  _TESTCASES_H
