/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITCASE1

	/* Calling C case1 functions */
	/* BEGIN-AUTOGENERATED-C-CASE1-FUNCTION-CALLS */

	/* END-AUTOGENERATED-C-CASE1-FUNCTION-CALLS */





#ifdef __cplusplus
	/* Calling C++ case1 functions */
	/* BEGIN-AUTOGENERATED-CPP-CASE1-FUNCTION-CALLS */
	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_74::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_74::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_44::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_44::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_08::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_08::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_22::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_22::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_61::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_61::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_13::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_13::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_82::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_82::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_07::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_07::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_34::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_34::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_17::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_17::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_54::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_54::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_54::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_54::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_12::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_12::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_22::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_22::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_45::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_45::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_07::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_07::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_01::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_01::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_67::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_67::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_02::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_02::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_42::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_42::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_53::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_53::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_83::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_83::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_04::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_04::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_10::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_10::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_42::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_42::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_17::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_17::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_84::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_84::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_74::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_74::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_33::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_33::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_32::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_32::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_82::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_82::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_08::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_08::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_09::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_09::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_68::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_68::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_52::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_52::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_81::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_81::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_84::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_84::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_52::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_52::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_03::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_03::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_41::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_41::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_01::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_01::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_41::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_41::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_15::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_15::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_06::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_06::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_67::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_67::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_10::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_10::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_83::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_83::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_34::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_34::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_21::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_21::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_18::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_18::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_05::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_05::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_18::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_18::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_16::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_16::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_83::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_83::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_05::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_05::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_43::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_43::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_11::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_11::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_02::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_02::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_73::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_73::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_51::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_51::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_65::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_65::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_81::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_81::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_43::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_43::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_62::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_62::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_66::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_66::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_63::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_63::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_21::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_21::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_31::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_31::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_63::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_63::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_72::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_72::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_03::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_03::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_66::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_66::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_65::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_65::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_64::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_64::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_53::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_53::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_04::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_04::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_31::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_31::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_73::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_73::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_45::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_45::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_32::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_32::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_83::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_83::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_33::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_33::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_62::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_62::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_14::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_14::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_84::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_84::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_16::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_16::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_06::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_06::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_51::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_51::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_64::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_64::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_44::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_44::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_72::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_72::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_09::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_09::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_11::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_11::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_14::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_14::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_84::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_84::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_12::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_12::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_61::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_61::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_68::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_68::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_13::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_13::case1();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_15::case1();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_15::case1();

	/* END-AUTOGENERATED-CPP-CASE1-FUNCTION-CALLS */

#endif /* __cplusplus */

#endif /* OMITCASE1 */

#ifndef OMITCASE0

	/* Calling C case0 functions */
	/* BEGIN-AUTOGENERATED-C-CASE0-FUNCTION-CALLS */

	/* END-AUTOGENERATED-C-CASE0-FUNCTION-CALLS */




	
#ifdef __cplusplus
	/* Calling C++ case0 functions */
	/* BEGIN-AUTOGENERATED-CPP-CASE0-FUNCTION-CALLS */
	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_74::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_74::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_44::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_44::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_08::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_08::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_22::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_22::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_61::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_61::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_13::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_13::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_82::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_82::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_07::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_07::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_34::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_34::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_17::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_17::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_54::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_54::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_54::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_54::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_12::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_12::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_22::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_22::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_45::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_45::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_07::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_07::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_01::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_01::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_67::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_67::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_02::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_02::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_42::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_42::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_53::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_53::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_83::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_83::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_04::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_04::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_10::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_10::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_42::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_42::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_17::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_17::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_84::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_84::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_74::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_74::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_33::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_33::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_32::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_32::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_82::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_82::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_08::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_08::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_09::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_09::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_68::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_68::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_52::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_52::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_81::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_81::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_84::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_84::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_52::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_52::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_03::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_03::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_41::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_41::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_01::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_01::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_41::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_41::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_15::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_15::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_06::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_06::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_67::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_67::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_10::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_10::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_83::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_83::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_34::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_34::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_21::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_21::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_18::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_18::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_05::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_05::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_18::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_18::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_16::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_16::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_83::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_83::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_05::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_05::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_43::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_43::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_11::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_11::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_02::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_02::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_73::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_73::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_51::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_51::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_65::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_65::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_81::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_81::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_43::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_43::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_62::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_62::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_66::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_66::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_63::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_63::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_21::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_21::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_31::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_31::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_63::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_63::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_72::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_72::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_03::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_03::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_66::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_66::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_65::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_65::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_64::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_64::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_53::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_53::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_04::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_04::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_31::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_31::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_73::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_73::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_45::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_45::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_32::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_32::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_83::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_83::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_33::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_33::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_62::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_62::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_14::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_14::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_84::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_84::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_16::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_16::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_06::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_06::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_51::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_51::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_64::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_64::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_44::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_44::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_72::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_72::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_09::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_09::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_11::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_11::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_14::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_14::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_84::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_84::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_12::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_12::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_61::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_61::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_68::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_68::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_13::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_w32CreateFile_13::case0();

	printLine("Calling CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_15::case0();");
	CWE23_Relative_Path_Traversal__wchar_t_listen_socket_open_15::case0();

	/* END-AUTOGENERATED-CPP-CASE0-FUNCTION-CALLS */
	
#endif /* __cplusplus */

#endif /* OMITCASE0 */

	return 0;

} 
